### ISSUE TITLE
[Feature request] Instructions?

### ISSUE THREAD

**Issue by jayschuster** [LukeStrazz/StrazzTunedBuddy#3]
I'm interested in making a couple of these for friends and I'm pretty sure I can figure out how to make it work, but if you do have any instructions that might make it easier that would be really cool :)
Also, do you have any specific product recommendations for the OLED display? I found a couple on Adafruit but they vary in size and price, so it'd be cool to verify the exact specs.
Thanks for the cool project!

**Comment by jayschuster** [comment]
oops

**Comment by LukeStrazz** [comment]
Hello! ReadMe should include the proper equipment, if you need further assistance assembling let me know! Everything is plug and play after you connect the correct terminals.
